# Generated by Django 5.0.6 on 2024-05-13 02:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TCTApp2', '0002_remove_historicalibanxtask11_history_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IbanxTask',
            new_name='Categorytwo',
        ),
        migrations.RenameModel(
            old_name='IbanxTask2',
            new_name='Categorytwo2',
        ),
        migrations.RenameModel(
            old_name='IbanxTask3',
            new_name='Categorytwo3',
        ),
        migrations.RenameModel(
            old_name='HistoricalIbanxTask',
            new_name='HistoricalCategorytwo',
        ),
        migrations.RenameModel(
            old_name='HistoricalIbanxTask2',
            new_name='HistoricalCategorytwo2',
        ),
        migrations.RenameModel(
            old_name='HistoricalIbanxTask3',
            new_name='HistoricalCategorytwo3',
        ),
        migrations.AlterModelOptions(
            name='historicalcategorytwo',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical categorytwo', 'verbose_name_plural': 'historical categorytwos'},
        ),
        migrations.AlterModelOptions(
            name='historicalcategorytwo2',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical categorytwo2', 'verbose_name_plural': 'historical categorytwo2s'},
        ),
        migrations.AlterModelOptions(
            name='historicalcategorytwo3',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical categorytwo3', 'verbose_name_plural': 'historical categorytwo3s'},
        ),
    ]
