# Generated by Django 5.0.6 on 2024-05-15 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TCTApp2', '0003_rename_ibanxtask_categorytwo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorytwo',
            name='client',
            field=models.CharField(db_index=True, default='Category One', max_length=100),
        ),
        migrations.AlterField(
            model_name='categorytwo',
            name='question_1',
            field=models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Restriced', 'Restricted'), ('Prohibited', 'Prohibited')], max_length=100, verbose_name='Level of Risk?'),
        ),
        migrations.AlterField(
            model_name='categorytwo',
            name='question_4',
            field=models.CharField(blank=True, choices=[('Google', 'Google'), ('Facebook', 'Facebook'), ('LinkedIn', 'LinkedIn'), ('Others', 'Others')], max_length=100, verbose_name='Social Media Site'),
        ),
        migrations.AlterField(
            model_name='categorytwo2',
            name='client',
            field=models.CharField(db_index=True, default='Category One', max_length=100),
        ),
        migrations.AlterField(
            model_name='categorytwo3',
            name='client',
            field=models.CharField(db_index=True, default='Category One', max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalcategorytwo',
            name='client',
            field=models.CharField(db_index=True, default='Category One', max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalcategorytwo',
            name='question_1',
            field=models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Restriced', 'Restricted'), ('Prohibited', 'Prohibited')], max_length=100, verbose_name='Level of Risk?'),
        ),
        migrations.AlterField(
            model_name='historicalcategorytwo',
            name='question_4',
            field=models.CharField(blank=True, choices=[('Google', 'Google'), ('Facebook', 'Facebook'), ('LinkedIn', 'LinkedIn'), ('Others', 'Others')], max_length=100, verbose_name='Social Media Site'),
        ),
        migrations.AlterField(
            model_name='historicalcategorytwo2',
            name='client',
            field=models.CharField(db_index=True, default='Category One', max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalcategorytwo3',
            name='client',
            field=models.CharField(db_index=True, default='Category One', max_length=100),
        ),
    ]
