# Generated by Django 5.0.6 on 2024-05-13 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TCTApp', '0003_historicalnoiretask3_noiretask3'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NoireTask',
            new_name='Categoryone',
        ),
        migrations.RenameModel(
            old_name='NoireTask2',
            new_name='Categoryone2',
        ),
        migrations.RenameModel(
            old_name='NoireTask3',
            new_name='Categoryone3',
        ),
        migrations.RenameModel(
            old_name='HistoricalNoireTask',
            new_name='HistoricalCategoryone',
        ),
        migrations.RenameModel(
            old_name='HistoricalNoireTask2',
            new_name='HistoricalCategoryone2',
        ),
        migrations.RenameModel(
            old_name='HistoricalNoireTask3',
            new_name='HistoricalCategoryone3',
        ),
        migrations.AlterModelOptions(
            name='historicalcategoryone',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical categoryone', 'verbose_name_plural': 'historical categoryones'},
        ),
        migrations.AlterModelOptions(
            name='historicalcategoryone2',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical categoryone2', 'verbose_name_plural': 'historical categoryone2s'},
        ),
        migrations.AlterModelOptions(
            name='historicalcategoryone3',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical categoryone3', 'verbose_name_plural': 'historical categoryone3s'},
        ),
    ]
