# Generated by Django 5.0.6 on 2024-05-15 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TCTApp', '0005_guestuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestuser',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='guestuser',
            name='first_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='guestuser',
            name='last_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
