name: DjangoTest

on:
  push:
    branches:
      - main
      - v1

  pull_request:
    branches:
      - main
      - v1

# on:
#   schedule:
#       - cron:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Python Setup
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    - name: Install Dependencies
      run:
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Check Errors Linter
      run: |
        pip install flake8
        flake8
    - name: Coverage Report
      run: |
        pip install coverage
        coverage run manage.py test
        coverage report
    - name: Project Tests
      run: |
        python manage.py test

  